[build-system]
requires = [
  "setuptools >= 80",
  "setuptools_scm[toml] >= 8",
]
build-backend = 'setuptools.build_meta'

[project]
name="NLR-reV"
dynamic = ["version"]
description = "National Laboratory of the Rockies' (NLR's) reV model"
readme = {file = "README.rst", content-type = "text/x-rst"}
authors = [
  {name = "Galen Maclaurin", email = "galen.maclaurin@nlr.gov"},
]
maintainers = [
  {name = "Grant Buster", email = "gbuster@nlr.gov"},
  {name = "Paul Pinchuk", email = "ppinchuk@nlr.gov"},
]
license = "BSD-3-Clause"
keywords = ["reV", "NLR"]
requires-python = ">= 3.11"
classifiers=[
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Natural Language :: English",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "NLR-GAPs>=0.9.1",
  "NREL-NRWAL>=0.0.11",
  "NREL-PySAM~=7.0.0",
  "NLR-rex>=0.5.0",
  "numpy>=2.4.2,<3",
  "packaging>=24.2,<25",
  "plotly>=6.0.1,<7",
  "plotting>=0.0.7,<0.1",
  "shapely>=2.0.7,<3",
]

[project.optional-dependencies]
test = [
  "pytest>=8.4.0,<9",
]
dev = [
  "flake8",
  "pre-commit",
  "pylint",
]
doc = [
  "ghp-import>=2.1.0,<3",
  "myst-parser>=5.0.0",
  "sphinx>=8.2.3,<9",
  "sphinx-click>=6.0.0,<7",
  "sphinx-copybutton>=0.5.2,<0.6",
  "sphinx-tabs>=3.4.1,<4",
  "sphinx_rtd_theme>=3.1.0,<4",
]
hsds = [
  "hsds>=0.8.4,<1",
]
build = [
  "build>=1.2.2,<2",
  "pkginfo>=1.10.0,<2",
  "twine>=6.1.0,<7",
]

[project.urls]
homepage = "https://www.nlr.gov/gis/renewable-energy-potential"
documentation = "https://natlabrockies.github.io/reV/"
repository = "https://github.com/NatLabRockies/reV"

[project.scripts]
reV = "reV.cli:main"
reV-bespoke = "reV.bespoke.cli_bespoke:main"
reV-collect = "reV.handlers.cli_collect:main"
reV-econ = "reV.econ.cli_econ:main"
reV-gen = "reV.generation.cli_gen:main"
reV-multiyear = "reV.handlers.cli_multi_year:main"
reV-supply-curve-aggregation = "reV.supply_curve.cli_sc_aggregation:main"
reV-supply-curve = "reV.supply_curve.cli_supply_curve:main"
reV-nrwal = "reV.nrwal.cli_nrwal:main"
reV-rep-profiles = "reV.rep_profiles.cli_rep_profiles:main"
reV-QA-QC = "reV.qa_qc.cli_qa_qc:main"
reV-hybrids = "reV.hybrids.cli_hybrids:main"
reV-project-points = "reV.config.cli_project_points:project_points"


[tool.setuptools.packages]
find = { include = ["reV*"] }

[tool.setuptools.dynamic]
version = {attr = "reV.version.__version__"}

[tool.setuptools_scm]
# Don't try to guess anything from Git. Only use what is in the version file.
version_scheme = "no-guess-dev"
local_scheme = "no-local-version"


[tool.coverage.run]
branch = true

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_also = [
  # Have to re-enable the standard pragma
  "pragma: no cover",

  # Don't complain about missing debug-only code:
  "if self\\.debug",

  # Don't complain about repr methods
  "def __repr__",
  "def _repr_markdown_",

  # Don't complain about data I/O code
  "def load*",
  "def _load*",

  # Don't complain if tests don't hit defensive assertion code:
  "raise AssertionError",
  "raise NotImplementedError",

  # Don't complain if non-runnable code isn't run:
  "if __name__ == .__main__.:",

  # Don't complain about abstract methods, they aren't run:
  "@(abc\\.)?abstractmethod",

  # Don't complain about logging debugging functions
  "def print_logging_info*",
  "def __cls_name",
]

omit = [
  # omit test files
  "tests/*",
  # omit init files
  "__init__.py",
  # omit version file
  "version.py",
  # omit pixi files
  ".pixi/*",
]


[tool.pytest.ini_options]
addopts = "--disable-warnings"
testpaths = ["tests"]
