name: reVX Pytests

concurrency:
  group: revx-tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: checkout reV
      uses: actions/checkout@v7.0.1
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 1
        path: reV
    - name: checkout reVX
      uses: actions/checkout@v7.0.1
      with:
        repository: NatLabRockies/reVX
        fetch-depth: 1
        path: reVX
    - name: Set up Python
      uses: conda-incubator/setup-miniconda@v4.0.1
      with:
        auto-update-conda: true
        python-version: 3.11
    - name: Install reV dependencies
      working-directory: ./reV
      shell: bash -l {0}
      run: |
        conda install pip pandas
        pip install -e .
    - name: Install reVX dependencies
      working-directory: ./reVX
      shell: bash -l {0}
      run: |
        conda install rtree pip pytest
        pip install -e .
        pip install HOPP==0.0.5
    - name: Run reVX pytest
      working-directory: ./reVX
      shell: bash -l {0}
      run: |
        pytest -v --disable-warnings
